
server:
  port: 8092

spring:
  application:
    name: sso-demo-2

sq:
  sso:
    client-id: siques-1
    client-secret: 123456
    redirect-uri: http://localhost:8091/callback.html
    access-token-uri: http://localhost:9001/uaa/oauth/token
    user-info-uri: http://localhost:9001/cor-business/users/current