server:
  port: 9001
siques:
  trace:
    enable: true

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      #添加跨域的配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: core-business   #路由id 没有固定规则但要求唯一，配合服务名
          #          uri: http://localhost:8001 # 匹配提供服务的路由地址
          uri: lb://core-business
          predicates:
            - Path=/core/**    #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1
        - id: search-center  #路由id 没有固定规则但要求唯一，配合服务名
          uri: lb://search-center
          predicates:
            - Path=/search/**    #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1
        - id: uaa-server  #路由id 没有固定规则但要求唯一，配合服务名
          uri: lb://uaa-server
          predicates:
            - Path=/uaa/**    #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: http://nacos.siques.cn:8848
        namespace: 5642eb84-60d0-42f3-83d7-1fb41c965cf2
        username: nacos
        password: heshenghao
        group: DEV_GROUP
    sentinel:
      transport:
        dashboard: 139.198.189.114:8858 # sentinel面板的启动端口
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      datasource: #添加Nacos数据源配置
        flow:
          nacos:
            namespace: 2298d310-d84b-49f5-8714-2346876d8457
            username: nacos
            password: heshenghao
            server-addr: http://nacos.siques.cn:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP  # nacos配置组
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            data-type: json
            rule-type: flow

