server:
  port: 8083
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8984/oauth/check_token
      jwt:
        key-alias: webApp
        # 如果没有此项会去请求授权服务器获取
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkF9SyMHeGAsLMwbPsKj/
          xpEtS0iCe8vTSBnIGBDZKmB3ma20Ry0Uzn3m+f40RwCXlxnUcvTw7ipoz0tMQERQ
          b3X4DkYCJXPK6pAD+R9/J5odEwrO2eysByWfcbMjsZw2u5pH5hleMS0YqkrGQOxJ
          pzlEcKxMePU5KYTbKUJkhOYPY+gQr61g6lF97WggSPtuQn1srT+Ptvfw6yRC4bdI
          0zV5emfXjmoLUwaQTRoGYhOFrm97vpoKiltSNIDFW01J1Lr+l77ddDFC6cdiAC0H
          5/eENWBBBTFWya8RlBTzHuikfFS1gP49PZ6MYJIVRs8p9YnnKTy7TVcGKY3XZMCA
          mwIDAQAB
          -----END PUBLIC KEY-----
        key-uri: http://localhost:8984/oauth/token_key
      id: test
    client:
      client-id: webApp
      client-secret: 123456
      access-token-uri: http://localhost:8984/oauth/token
      user-info-uri: http://localhost:8984/oauth/user
      scope: READ
spring:
  main:
    banner-mode: off
  #  rabbitmq:
#    host: 106.54.247.224
#    username: admin
#    password: heshenghao
#    port: 5672
#    virtual-host: my_vhost
#    #    解决消息到达中心之前出现问题的情况
#    publisher-confirm-type: simple
  cloud:
    nacos:
      discovery:
        server-addr: 139.198.189.114:8848 #配置Nacos地址
        namespace: 5642eb84-60d0-42f3-83d7-1fb41c965cf2
  datasource:
    name: druidSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.247.224:3306/siques?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
        enabled: true
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: ""
  multiple-source:
    - url: jdbc:mysql://106.54.247.224:3306/mango-sound?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: l1itdhjaoiqw32kwqe$5asasd*a21
    - url: jdbc:mysql://127.0.0.1:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: l1itdhjaoiqw32kwqe$5asasd*a21
    - url: jdbc:mysql://127.0.0.1:3306/nest?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: l1itdhjaoiqw32kwqe$5asasd*a21
    - url: jdbc:mysql://106.54.247.224:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: l1itdhjaoiqw32kwqe$5asasd*a21

  boot:
  #    admin:
  #      client:
  #        url: "http://localhost:8090"

  application:
    name: core-business
  redis:
    host: 106.54.247.224
    port: 6379
    database: 0
    expiration: 1800
    password: heshenghao
#开启控制台打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper*/*.xml
  type-aliases-package: cn.central.entity
  global-config:
    banner: false
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql
# 健康监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
swagger:
  #  配置扫描swagger包
  base-package: cn.central.controller

# 开启审计日志
siques:
  audit-log:
    enabled: true
  trace:
    enable: true
#    log-type: db
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/mango?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#      username: root
#      password: l1itdhjaoiqw32kwqe$5asasd*a21
