server:
  port: 8984

spring:
  application:
    name: SiquesOauth
  datasource:
    url: jdbc:mysql://106.54.247.224:3306/siques?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.54.247.224
    port: 6379
    database: 1
    expiration: 1800
    password: heshenghao

logging:
  level:
    org.springframework.security: debug
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
