server:
  port: 8984
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION
siques:
  oauth2:
    uaa-server: true
    token:
      store:
        type: redisJwk
  security:
    ignore:
      - /validate/captcha
      - /client/**
spring:
  main:
    banner-mode: off
  application:
    #    User Account and Authentication (UAA)
    name: uaa-server
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://mysql.siques.cn/siques-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: l1itdhjaoiqw32kwqe
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis.siques.cn
    port: 6379
    database: 1
    expiration: 1800
    password: heshenghao
  cloud:
    nacos:
      discovery:
        server-addr: http://nacos.siques.cn
        namespace: 5642eb84-60d0-42f3-83d7-1fb41c965cf2
        username: nacos
        password: heshenghao
        group: DEV_GROUP
logging:
  level:
    org.springframework.security: debug
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8984/oauth/check_token
      jwt:
        key-alias: oauthApp
        # 如果没有此项会去请求授权服务器获取
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkF9SyMHeGAsLMwbPsKj/
          xpEtS0iCe8vTSBnIGBDZKmB3ma20Ry0Uzn3m+f40RwCXlxnUcvTw7ipoz0tMQERQ
          b3X4DkYCJXPK6pAD+R9/J5odEwrO2eysByWfcbMjsZw2u5pH5hleMS0YqkrGQOxJ
          pzlEcKxMePU5KYTbKUJkhOYPY+gQr61g6lF97WggSPtuQn1srT+Ptvfw6yRC4bdI
          0zV5emfXjmoLUwaQTRoGYhOFrm97vpoKiltSNIDFW01J1Lr+l77ddDFC6cdiAC0H
          5/eENWBBBTFWya8RlBTzHuikfFS1gP49PZ6MYJIVRs8p9YnnKTy7TVcGKY3XZMCA
          mwIDAQAB
          -----END PUBLIC KEY-----
        key-uri: http://localhost:8984/oauth/token_key
      id: test
    client:
      client-id: oauthApp
      client-secret: 123456
      access-token-uri: http://localhost:8984/oauth/token
      user-info-uri: http://localhost:8984/oauth/user
      scope: READ


