security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8984/oauth/check_token
      jwt:
        key-alias: webApp
        # 如果没有此项会去请求授权服务器获取
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkF9SyMHeGAsLMwbPsKj/
          xpEtS0iCe8vTSBnIGBDZKmB3ma20Ry0Uzn3m+f40RwCXlxnUcvTw7ipoz0tMQERQ
          b3X4DkYCJXPK6pAD+R9/J5odEwrO2eysByWfcbMjsZw2u5pH5hleMS0YqkrGQOxJ
          pzlEcKxMePU5KYTbKUJkhOYPY+gQr61g6lF97WggSPtuQn1srT+Ptvfw6yRC4bdI
          0zV5emfXjmoLUwaQTRoGYhOFrm97vpoKiltSNIDFW01J1Lr+l77ddDFC6cdiAC0H
          5/eENWBBBTFWya8RlBTzHuikfFS1gP49PZ6MYJIVRs8p9YnnKTy7TVcGKY3XZMCA
          mwIDAQAB
          -----END PUBLIC KEY-----
        key-uri: http://localhost:8984/oauth/token_key
      id: test
    client:
      client-id: webApp
      client-secret: 123456
      access-token-uri: http://localhost:8984/oauth/token
      user-info-uri: http://localhost:8984/oauth/user
      scope: READ
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: search-center
  elasticsearch:
    rest:
      uris: 139.198.189.114:9200
      username: elastic
      password: heshenghao
  cloud:
    nacos:
      discovery:
        server-addr: 139.198.189.114:8848 #配置Nacos地址
        namespace: 5642eb84-60d0-42f3-83d7-1fb41c965cf2
  datasource:
    url: jdbc:mysql://106.54.247.224:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
server:
  port: 7100

swagger:
  #  配置扫描swagger包
  base-package: cn.central

siques:
  indices:
    show: sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*
#  swagger:
#    enabled: true
#    title: 搜索中心
#    description: 搜索中心接口文档
#    version: 1.0
#    base-package: com.central.search.controller