{
 "title": "Nacos",
 "tags": [
  "prometheus",
  "nacos"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "nacos monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nacos_monitor{exported_name=\"configCount\"})"
    }
   ]
  },
  {
   "title": "service count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{exported_name='domCount'})"
    }
   ]
  },
  {
   "title": "ip count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{exported_name='ipCount'})"
    }
   ]
  },
  {
   "title": "config count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{exported_name='configCount', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{exported_name='longPolling'})"
    }
   ]
  },
  {
   "title": "config push total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{exported_name='getConfig', instance=~'$instance'}) by (exported_name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "content": "<center>\n<a href=\"https://nacos.io\">\n<img src=\"https://nacos.io/img/nacos.png\" style=\"height: 50px;\" >\n</a>\n</center>"
  },
  {
   "title": "cpu",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "notify rt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nacos_timer_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacos_timer_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  { "title": "alert list", "type": "alertlist", "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4 } },
  {
   "title": "qps",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "rt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='avgPushCost', instance=~'$instance'})"
    }
   ]
  },
  { "title": "nacos detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'/v1/cs/configs|/nacos/v1/ns', instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri) * 1000"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "repeat": "group",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{exported_name='longPolling', instance=~'$instance'})",
     "legendFormat": "longPolling"
    }
   ]
  },
  {
   "title": "load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "leaderStatus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{exported_name='leaderStatus', instance=~'$instance'})",
     "legendFormat": "leaderStatus"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{exported_name='avgPushCost', instance=~'$instance'})",
     "legendFormat": "avgPushCost"
    }
   ]
  },
  {
   "title": "maxPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{exported_name='maxPushCost', instance=~'$instance'})",
     "legendFormat": "maxPushCost"
    }
   ]
  },
  {
   "title": "config statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{exported_name='publish', instance=~'$instance'}) by (name)",
     "legendFormat": "publish config"
    },
    {
     "expr": "sum(nacos_monitor{exported_name='getConfig', instance=~'$instance'}) by (name)",
     "legendFormat": "get config"
    }
   ]
  },
  {
   "title": "health check",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_monitor{exported_name=~'.*HealthCheck', instance=~'$instance'}[1m])) by (name) * 60"
    }
   ]
  },
  { "title": "nacos alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "cpu alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_cpu_usage) * 100", "legendFormat": "cpu_usage" }
   ]
  },
  {
   "title": "load  alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_load_average_1m)", "legendFormat": "load_average" }
   ]
  },
  {
   "title": "memory alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/sum(jvm_memory_max_bytes{area=\"heap\"}) * 100",
     "legendFormat": "memory_used_rate"
    }
   ]
  },
  {
   "title": "threads alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads)",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "gc alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[5m])) * 300",
     "legendFormat": "gc_count"
    }
   ]
  },
  {
   "title": "notify task alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{exported_name='notifyTask'})",
     "legendFormat": "notifyTask"
    }
   ]
  },
  {
   "title": "rt alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m]))/sum(rate(http_server_requests_seconds_count[1m])) * 1000",
     "legendFormat": "rt_rate"
    }
   ]
  },
  {
   "title": "long polling alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{exported_name='longPolling'})",
     "legendFormat": "longPolling"
    }
   ]
  },
  {
   "title": "config unhealth exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='unhealth'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "db exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='db'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "failed push alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='failedPush'})"
    }
   ]
  },
  {
   "title": "illegalArgument exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='illegalArgument'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming disk exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='disk'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "config notify exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='configNotify'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming leader send beat failed exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='leaderSendBeatFailed'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "nacos exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='nacos'}[1m])) * 60"
    }
   ]
  }
 ]
}