
server:
  port: 8091

spring:
  application:
    name: sso-demo

sq:
  sso:
    client-id: siques
    client-secret: 123456
    redirect-uri: http://127.0.0.1:8091/callback.html
    access-token-uri: http://127.0.0.1:9001/uaa/oauth/token
    user-info-uri: http://127.0.0.1:9001/cor-business/users/current