
server:
  port: 8091

spring:
  application:
    name: sso-demo

siques:
  api-uaa:
    url: http://127.0.0.1:9001/uaa/oauth

security:
  oauth2:
    sso:
      login-path: /singleLogin

    client:
      client-id: siques
      client-secret: 123456
      access-token-uri: ${siques.api-uaa.url}/token
      user-authorization-uri: ${siques.api-uaa.url}/authorize
    resource:
      token-info-uri: ${siques.api-uaa.url}/check_token