version: "3.3"

services:
  canal-adapter:
    build: .
    ports:
      - 8089:8089
    volumes:
      - ./sys_user.yml:/opt/canal/adapter/conf/es7/sys_user.yml
      - ./nest_doc.yml:/opt/canal/adapter/conf/es7/nest_doc.yml
      - ./application.yml:/opt/canal/adapter/conf/application.yml
      - ./data/:/opt/canal/adapter/logs/adapter/
    restart: always
    environment:
      TZ: Asia/Shanghai