version: "3.3"

services:
  canal-adapter:
    build: .
    ports:
      - 8089:8089
    volumes:
      - ./siques_admin_user.yml:/opt/canal/adapter/conf/es7/siques_admin_user.yml
      - ./siques_doc.yml:/opt/canal/adapter/conf/es7/siques_doc.yml
      - ./application.yml:/opt/canal/adapter/conf/application.yml
      - ./data/:/opt/canal/adapter/logs/adapter/
    restart: always
    environment:
      TZ: Asia/Shanghai