seata:
  tx-service-group: test_tx_service_group
  config:
    type: nacos
    nacos:
      serverAddr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      namespace: 8e7d4a74-8465-4c16-a8df-75c7a5fdb834
      username: nacos
      password: heshenghao
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      username: nacos
      namespace: 8e7d4a74-8465-4c16-a8df-75c7a5fdb834
      password: heshenghao