version: "3"

services:

  seata-server:
    image: seataio/seata-server:latest
    hostname: seata-server
    ports:
      - 8091:8091
    environment:
      - SEATA_IP= 139.198.176.14
      - STORE_MODE=db
      - SEATA_PORT=8091
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    expose:
      - 8091
    volumes:
      - ./path/to/config_file:/root/seata-config