spring:
  datasource:
    url: jdbc:mysql://106.54.247.224:3306/seata-demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
    driver-class-name: com.mysql.cj.jdbc.Driver

seata:
  tx-service-group: test_tx_service_group
  config:
    type: nacos
    nacos:
      serverAddr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      username: nacos
      password: heshenghao
      namespace: 8e7d4a74-8465-4c16-a8df-75c7a5fdb834
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      username: nacos
      password: heshenghao
      namespace: 8e7d4a74-8465-4c16-a8df-75c7a5fdb834