FROM node:12.13.0
WORKDIR /usr/src/nuxt
ENV HOST 0.0.0.0

COPY . .
# COPY .env .env
COPY .npmrc .npmrc
RUN  npm config set registry https://registry.npm.taobao.org

# RUN npm  rebuild node-sass
RUN  npm install
RUN  npm run build 
RUN  npm cache clean --force

EXPOSE 3002
CMD ["npm","start"]