version: "3"

services:
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    restart: always
    volumes:
      - ./proc:/host/proc
      - ./sys:/host/sys
      - /:/rootfs

