version: "3"

services:
  canal:
    image: canal/canal-server:latest
    ports:
      - 11111:11111
    volumes:
      - ./canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./siques-doc/instance.properties:/home/admin/canal-server/conf/siques-doc/instance.properties
      - ./siques-admin-user/instance.properties:/home/admin/canal-server/conf/siques-admin-user/instance.properties
      - ./logs/:/home/admin/canal-server/logs/
    restart: always
 